config/routes.rb
Calendary::Application.routes.draw do
  root :to => "root#root"

  resources :users, :only => [:new, :create, :destroy] do
  	resources :calendars, :only => [:index]
  end
  resource :user, :only => [:show]

  resource :session, :only => [:new, :create, :destroy]

  resources :calendars, :only => [:create, :update, :show, :destroy] do
  	# resource :event, :only => []
  	resources :events, :only => [:create, :update, :destroy]
  end
  	resources :events, :only => [:show]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalendarApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"></script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header"><% if logged_in? %>
	<form method="POST" action="<%= session_url %>">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		<input type="hidden" name="_method" value="DELETE">
		<%= current_user.username.capitalize %>, 
		<input type="submit" class="logout" value="log out">
	</form>	
<% else %>
	<ul> 
		<li><%= link_to "Log In", new_session_url %></li>
		<li><%= link_to "Create User", new_user_url %></li>
	</ul>
<% end %></div>

<% if flash[:errors] %>
	<div id="errors">
		<% if flash[:errors].class == Array %>		
		<ul>
			<% flash[:errors].each do |error| %>
				<li><%= error %></li>
			<% end %>
		</ul>
		<% else %>
			<%= flash[:errors] %>
		<% end %>
	</div>
<% end %>

<%= yield %>



</body>
</html>